# Generated by Django 4.1.6 on 2023-02-05 11:49

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRequisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requisition_id",
                    models.UUIDField(blank=True, null=True, unique=True),
                ),
                ("institution_id", models.UUIDField(unique=True)),
                (
                    "status",
                    django_enum.fields.EnumSmallIntegerField(
                        choices=[(0, "In Progress"), (1, "Success"), (-1, "Failed")],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.UUIDField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requisition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nordigen_api.userrequisition",
                    ),
                ),
            ],
        ),
    ]
