# Generated by Django 4.1.6 on 2023-02-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nordigen_api", "0002_alter_userrequisition_institution_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrequisition",
            name="reference_id",
            field=models.UUIDField(
                default="91683e5e-447a-4ffa-93be-4106db32de96", unique=True
            ),
            preserve_default=False,
        ),
    ]
